wall_follower:
  ros__parameters:
    # PID parameters - tuned for very high speed
    kp: 2.0       # Increased for sharper steering response
    ki: 0.001     # Keep same minimal integral
    kd: 1.5       # Increased for better stability at higher speed
    
    # Wall following parameters
    desired_distance: 0.8    # Reduced target distance for tighter cornering
    forward_speed: 3.0     # Increased base forward speed
    min_safe_distance: 0.6   # Increased safety margin for higher speed
    max_steering_angle: 0.45  # Slightly increased max steering for tighter turns
    
    # Laser processing parameters
    min_angle: 0.785  # 45 degrees in radians
    max_angle: 1.57   # 90 degrees in radians 
