/**:
  ros__parameters:
    product_name: 'LDLiDAR_LD19'
    topic_name: 'scan'
    frame_id: 'base_laser'
    port_name: '/dev/sensors/lidar'
    port_baudrate: 230400
    laser_scan_dir: False
    enable_angle_crop_func: False
    angle_crop_min: 225.0
    angle_crop_max: 315.0
