manual_control_node:
  ros__parameters:
    joy_topic: "/joy"
    drive_topic: "/drive"
    ackermann_cmd_topic: "/ackermann_cmd"
    throttle_gain: 3.0
    throttle_multiplier: 2.0
    steering_gain: -0.335
    steering_offset: 0.0
    constant_throttle: 1.0
