/**:
  ros__parameters:
    ttc_threshold: 1.0
    restricted_min_angle: 3.141593
    restricted_max_angle: 6.283186
    min_speed_threshold: 0.15  # Minimum speed to activate TTC checking
    max_brake_speed: 0.0     # Speed to set when braking
    scan_topic: "/scan"
    odom_topic: "/ego_racecar/odom"
    drive_topic: "/drive"
