/**:
  ros__parameters:
    lookahead_dist: 0.6
    min_lookahead_dist: 0.5
    max_lookahead_dist: 0.8
    lookahead_ratio: 4.0
    max_speed: 1.0
    kp: 0.7
    max_steering_angle: 0.4
    n_pathpoints: 43
    window_size: 10
    csv_path:  "/root/f1tenth_ws/src/pure_pursuit_pkg/racelines/salon_jaime_v1_waypoints.csv"
    map_frame: "map"
    car_frame: "base_link"
    odom_topic: "/odom"
    drive_topic: "/drive"